Книжная библиотека
Kirill-sudar/learnJavascript pull request #4
Opened 2020-07-26 22:04 UTC by Kirill-sudar

2020-07-27 10:51 UTC, smartianin requested changes
Кирилл, почему файлы с итераторов попали в этот PR?

2020-07-27 10:51 UTC, smartianin commented on object.library.js
> +let obj = {
Пункт 1. Я просил создать объект library, `obj` => `library`

2020-07-27 10:51 UTC, smartianin commented on object.library.js
> +    Crime:[],
Пункт 3. У объекта можно указывать свойства в кавычках, я просил сделать именно так. `Crime` => `'Crime'`,  `scienceFiction` => `'Science fiction'` и тд.

2020-07-27 10:51 UTC, smartianin commented on object.library.js
> +    get getter(){
Пункт 4. Геттер объявляется на уровне объекта library и называть его нужно соответственно
`get getter` => `get genres`

2020-07-27 10:51 UTC, smartianin commented on object.library.js
> +  addBookToProperGenre(bookName,
Пункт 6. Где ты потерял 3й (первый по порядку) параметр genreName?

2020-07-27 10:51 UTC, smartianin commented on object.library.js
> +    books = this._genres[genreName];
Пункт 9. Ты не объявил переменную `books`

2020-07-27 10:51 UTC, smartianin commented on object.library.js
> +    genreName[randomINdex] = Math.floor(Math.random()*Crime.length);
Пункт 9. В пределах массива `books`, `Crime` => `books`
и объясни, зачем ты у строки genreName вызываешь рандомный элемент?

2020-07-27 10:51 UTC, smartianin commented on object.library.js
> +obj.addBookToProperGenre('Остров', 50)
Пункт 10. Я просил заполнить библиотеку как минимум 3мя книгами на каждый жанр.

2020-07-27 10:51 UTC, smartianin commented on object.library.js
> +myBook = addBookToProperGenre();
Пункт 11. `myBook` должна быть переменной и в неё ты записываешь результат с помощью вызова метода getRandomBook() у объекта library.

2020-07-27 10:55 UTC, smartianin requested changes

2020-07-27 10:55 UTC, smartianin commented on iterators.part2.js
>  let reduceIteratorTwo = iteratorArray.reduceRight( (sum, el) => {
Удали этот файл

2020-07-27 10:55 UTC, smartianin commented on object.library.js
> +  },
```suggestion
  addBookToProperGenre(genreName, bookName, bookPrice) {
    let book = {
        name: bookName,
        price: bookprice
    };
    this._genres[genreName].push(book);
  },
```

2020-07-28 21:04 UTC, Kirill-sudar commented on object.library.js
> +    genreName[randomINdex] = Math.floor(Math.random()*Crime.length);
по условию

2020-07-28 21:04 UTC, Kirill-sudar commented on object.library.js
> +    genreName[randomINdex] = Math.floor(Math.random()*Crime.length);
В пределах массива books, Crime => books 
я не совсем понял что ты имеешь ввиду

2020-07-29 10:08 UTC, smartianin commented on object.library.js
> +    genreName[randomINdex] = Math.floor(Math.random()*Crime.length);
У тебя уже есть массив `books`, вот его и бери

2020-07-30 15:58 UTC, smartianin reviewed
.

2020-07-30 15:58 UTC, smartianin commented on object.library.js
> +      let books = this._genres["Crime"];
Ты захардкодил "Crime", а тебе нужно обращаться к свойству через параметр `genreName`, и того выходит
 `let books = this._genres[genreName];`

2020-07-30 15:58 UTC, smartianin commented on object.library.js
> +      books[genreName] === Math.floor(Math.random()*(books.length));
Вот на этой строке, я вообще не понимаю что ты делаешь??? Читая твой код в лоб, выходит что ты сравниваешь равен ли массив книг индексу? Зачем ты это делаешь?

Тебе нужно просто сгенирировать случайный индекс в пределах длинны массива books

2020-07-30 15:58 UTC, smartianin commented on object.library.js
> +      books[genreName] === Math.floor(Math.random()*(books.length));
И лишь зачем вернуть уже конкретную книгу из массива books по индексу, который ты сгенерил случаным образом выше

2020-07-30 16:02 UTC, Kirill-sudar commented on object.library.js
> +      let books = this._genres["Crime"];
ааа,я так сначала сделал ,а потом подумал что мне нужно попасть в сам массив в свойстве

2020-08-04 20:57 UTC, merged